---
title: "Alpha diversity"
output: html_notebook
---

# Setup

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = file.path(getwd(), '..'))
```

```{r, include=FALSE, echo=FALSE}
library(here)
library(phyloseq)
library(tidyverse)
library(vegan)
```

# Read in data

## trnL
Note this is already trimmed to only those taxa identified to a food species, with duplicated taxa collapsed.
```{r}
# Read in last saved phyloseqs
ps <- 
     here('data', 'processed', 'phyloseq', 'trnL_combined_ps.rds') %>% 
     readRDS()

ps
```

# Alpha diversity

```{r}
alpha <- 
     estimate_richness(ps, measures = 'Observed') %>% 
     # Clean up formatting
     rownames_to_column(var = 'name') %>% 
     mutate(name = gsub('\\.', '-', name))

alpha
```

```{r}
# Join to read counts
samdf <- 
     data.frame(ps@sam_data) %>% 
     select(-name) %>% # SUBJ_WEEK_DATE format, incomplete across cohorts
     rownames_to_column(var = 'name')

alpha <- 
     samdf %>% 
     select(name, study, subj, reads_food) %>% 
     right_join(alpha)

alpha
```

```{r}
# Join to rarefied data
rarefaction.df <- 
     readRDS(
          here('data', 'processed', 'rarefaction',
             'Rarefied trnL counts (5,000 or 10,500 reads).rds')
          )
```

```{r}
alpha <- 
     rarefaction.df %>% 
     select(-obs) %>% # Already computed above
     full_join(alpha, .)

rm(rarefaction.df)
```

### vs. read counts

```{r}
# Make long-form data for plotting
alpha.long <- 
     alpha %>% 
     select(-starts_with('obs_rare_se')) %>% 
     pivot_longer(cols = c(Observed, obs_rare_5000, obs_rare_10500),
                  names_to = 'measure',
                  values_to = 'value') 
```

```{r}
ggplot(alpha.long, aes(x = reads_food, y = value)) +
     geom_point() +
     facet_wrap(~measure) +
     labs(x = 'Read depth', y = 'Alpha diversity') +
     theme_bw()
```
```{r}
cor.test(alpha$Observed, alpha$reads_food,
         alternative = 'greater',
         method = 'pearson')
```

```{r}
cor.test(alpha$obs_rare_5000, alpha$reads_food,
         alternative = 'greater',
         method = 'pearson')
```

```{r}
cor.test(alpha$obs_rare_10500, alpha$reads_food,
         alternative = 'greater',
         method = 'pearson')
```

## By subject 

```{r}
# Refactor subject IDs in order of descending median taxa observations
alpha.stats <- 
     alpha %>% 
     group_by(subj) %>% 
     summarize(med = median(obs_rare_10500, na.rm = TRUE), 
               sd = sd(obs_rare_10500, na.rm = TRUE)) %>% 
     arrange(desc(med))

alpha$subj <- factor(alpha$subj, levels = alpha.stats$subj)
```

```{r}
alpha %>% 
     ggplot(aes(x = subj, y = obs_rare_10500)) +
     geom_boxplot() +
     facet_wrap(~study, scales = 'free_x') +
     labs(x = 'Participant') +
     theme_bw() +
     theme(
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank(), 
          panel.grid.major.x = element_blank()
     )
```


```{r}
plotID <- paste(Sys.Date(), as.character(sample(000:999,1)), sep=".")
ggsave(here('results', 'miniseq', 'Combined', 'alpha diversity',
            paste0(plotID, '_Alpha diversity by study, raw.pdf')),
       height = 3, width = 5)
```

```{r}
alpha %>% 
     filter(study %in% c('Adult-1', 'Adult-2')) %>% 
     ggplot(aes(x = subj, y = obs_rare_10500, fill = study)) +
     geom_boxplot() +
     # facet_wrap(~study, scales = 'free_x') +
     labs(x = 'Participant', y = 'trnL richness') +
     scale_fill_manual(values = c('gray80', 'gray40')) +
     theme_bw() +
     theme(
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank(), 
          panel.grid.major.x = element_blank(),
          legend.position = c(0.9,0.8),
          legend.background = element_rect(color = 'black'),
          legend.title = element_blank()
     )
```

```{r}
adult.stats <- 
     alpha %>% 
     filter(study %in% c('Adult-1', 'Adult-2')) %>% 
     group_by(subj) %>% 
     summarize(med = median(obs_rare_10500,
                            na.rm = TRUE),
               sd = sd(obs_rare_10500,
                       na.rm = TRUE))

range(adult.stats$med, na.rm = T)
range(adult.stats$sd, na.rm = T)
```


```{r}
plotID <- paste(Sys.Date(), as.character(sample(000:999,1)), sep=".")

ggsave(here('results', 'manuscript', '1',
            paste0(plotID, '_B_Richness by subject, 5,000 read rarefaction.pdf')),
       height = 4, width = 6)
```


How does this change with filtering out of low quality samples?
What about at different phylogenetic levels?
Adding more comprehensive demographic data?