---
title: "Figure 2b-d, S6"
output:
  html_document:
    df_print: paged
    fig_width: 2.5
    fig_height: 4
    toc: true
    toc_float: true
---

# Setup

```{r, include=FALSE, echo=FALSE}
library(phyloseq)
library(tidyverse)
```

```{r include=FALSE, echo=FALSE}
# Plotting themes
theme_set(theme_bw() +
               theme(
                    axis.text = element_text(size = 12),
                    axis.title = element_text(size = 14,
                                              face = 'bold'),
                    strip.text = element_text(size = 12,
                                              face = 'bold')
                     )
)
```

# Read in data

```{r}
# trnL phyloseq object
ps <- readRDS('data/phyloseq_trnL.rds')

# alpha diversity
alpha <- read_csv('data/alpha.csv')

# dietary indices from DHQ3 FFQ
ffq <- read_csv('data/Adult-1 and Adult-2 dietary indices.csv')
```
# Pre-process

```{r}
# Filter trnL data to successfully sequenced Adult-1 and -2 samples
ps <- subset_samples(ps, study %in% c('Adult-1', 'Adult-2')) 
ps <- prune_samples(sample_sums(ps) > 0, ps)

# Move forward with pMR only
alpha <- 
     alpha |> 
     filter(grepl(name, pattern = 'CHOMP|ONR')) |> 
     filter(measure == 'Richness')
```

```{r}
# Add in relevant sample metadata
add <- 
     ps@sam_data |>
     data.frame() |> 
     rownames_to_column(var = 'row') |> 
     select(row, study, subj, CH_week, ONR_day) 

alpha <-
    left_join(add,
              alpha,
              by = c('row' = 'name'),
              multiple = 'all')
```

```{r}
# Average trnL richness within each subject
alpha.mean <-
     alpha |> 
     group_by(study, subj, measure, rarefied) |> 
     summarize(mean = mean(value, na.rm = TRUE)) |> 
     ungroup()
```

# Analyze

## Correlations

```{r}
# Join mean richness to PDI data
ffq <- 
     alpha.mean |> 
     left_join(ffq) |> 
     filter(pass_qc)
```

```{r}
fvs.plant <- 
     ffq |> 
     group_by(study, rarefied) |> 
     summarize(rho = cor.test(~ fvs_plant_residual + mean,
                           method = 'spearman',
                           exact = FALSE)$estimate,
               p = cor.test(~ fvs_plant_residual + mean,
                            method = 'spearman',
                           exact = FALSE)$p.value,
               .groups = 'keep') |> 
     ungroup() |> 
     mutate(ffq = 'FVS plant residual') 

fvs.animal <- 
     ffq |> 
     group_by(study, rarefied) |> 
     summarize(rho = cor.test(~ fvs_animal_residual + mean,
                           method = 'spearman',
                           exact = FALSE)$estimate,
               p = cor.test(~ fvs_animal_residual + mean,
                            method = 'spearman',
                           exact = FALSE)$p.value,
               .groups = 'keep') |> 
     ungroup() |> 
     mutate(ffq = 'FVS animal residual') 
     
hpdi <- 
     ffq |> 
     group_by(study, rarefied) |> 
     summarize(rho = cor.test(~ hPDI + mean,
                           method = 'spearman',
                           exact = FALSE)$estimate,
               p = cor.test(~ hPDI + mean,
                            method = 'spearman',
                           exact = FALSE)$p.value,
               .groups = 'keep') |> 
     ungroup() |>      
     mutate(ffq = 'hPDI') 
     
updi <- 
     ffq |> 
     group_by(study, rarefied) |> 
     summarize(rho = cor.test(~ uPDI + mean,
                           method = 'spearman',
                           exact = FALSE)$estimate,
               p = cor.test(~ uPDI + mean,
                            method = 'spearman',
                           exact = FALSE)$p.value,
               .groups = 'keep') |> 
     ungroup() |> 
     mutate(ffq = 'uPDI')  
     
hei.plant <- 
     ffq |> 
     group_by(study, rarefied) |> 
     summarize(rho = cor.test(~ hei_plant_all + mean,
                           method = 'spearman',
                           exact = FALSE)$estimate,
               p = cor.test(~ hei_plant_all + mean,
                            method = 'spearman',
                           exact = FALSE)$p.value,
               .groups = 'keep') |> 
     ungroup() |> 
     mutate(ffq = 'HEI plant') 

hei.nonplant <- 
     ffq |> 
     group_by(study, rarefied) |> 
     summarize(rho = cor.test(~ hei_non_plant + mean,
                           method = 'spearman',
                           exact = FALSE)$estimate,
               p = cor.test(~ hei_non_plant + mean,
                            method = 'spearman',
                           exact = FALSE)$p.value,
               .groups = 'keep') |> 
     ungroup() |> 
     mutate(ffq = 'HEI non-plant') 
```

```{r}
# Bind all together
spearman.results <- 
     bind_rows(
          fvs.plant,
          fvs.animal,
          hpdi,
          updi,
          hei.plant,
          hei.nonplant
     ) |> 
     mutate(ffq = factor(ffq,
                         levels = c('FVS plant residual',
                                    'FVS animal residual', 
                                    'hPDI',
                                    'uPDI',
                                    'HEI plant',
                                    'HEI non-plant'),
                         labels = c('FVS plant',
                                    'FVS animal', 
                                    'hPDI',
                                    'uPDI',
                                    'HEI plant',
                                    'HEI non-plant'))) |> 
     select(ffq, everything())
```

### FVS 
```{r}
spearman.results |> 
     filter(ffq == 'FVS plant') |> 
     arrange(rarefied)
```

```{r}
spearman.results |> 
     filter(ffq == 'FVS animal') |> 
     arrange(rarefied)
```

### PDI
```{r}
spearman.results |> 
     filter(ffq == 'hPDI') |> 
     arrange(rarefied)
```

```{r}
spearman.results |> 
     filter(ffq == 'uPDI') |> 
     arrange(rarefied)
```

### HEI-2015
```{r}
spearman.results |> 
     filter(ffq == 'HEI plant') |> 
     arrange(rarefied)
```

```{r}
spearman.results |> 
     filter(ffq == 'HEI non-plant') |> 
     arrange(rarefied)
```

## Plots

### FVS

```{r}
# Raw data
ffq |> 
     filter(rarefied == 'Raw') |> 
     ggplot(aes(x = fvs_plant_residual, y = mean)) +
     geom_point(size = 2, alpha = 0.6) +
     facet_wrap(~study,
                nrow = 2) +
     labs(x = 'FVS score residual\n(plant items)',
          y = 'Mean pMR')
```
```{r}
# ggsave('Fig 2b.pdf', device = cairo_pdf, height = 4, width = 2.5)
```

```{r}
ffq |> 
     filter(rarefied == 'Raw') |> 
     ggplot(aes(x = fvs_animal_residual, y = mean)) +
     geom_point(size = 2, alpha = 0.6) +
     facet_wrap(~study,
                nrow = 2) +
     ylim(0, 26) +
     labs(x = 'FVS score residual\n(animal items)',
          y = 'Mean pMR')
```

```{r}
# ggsave('Fig S6a.pdf', device = cairo_pdf, height = 4, width = 2.5)
```

### PDI

```{r}
ffq |> 
     filter(rarefied == 'Raw') |> 
     ggplot(aes(x = hPDI, y = mean)) +
     geom_point(size = 2, alpha = 0.6) +
     facet_wrap(~study,
                nrow = 2) +
     ylim(0, 26) +
     labs(y = 'Mean pMR',
          x = 'hPDI\n') 
```

```{r}
# ggsave('Fig 2c.pdf', device = cairo_pdf, height = 4, width = 2.5)
```

```{r}
ffq |> 
     filter(rarefied == 'Raw') |> 
     ggplot(aes(x = uPDI, y = mean)) +
     geom_point(size = 2, alpha = 0.6) +
     facet_wrap(~study,
                nrow = 2) +
     ylim(0, 26) +
     labs(y = 'Mean pMR',
          x = 'uPDI\n') 
```

```{r}
# ggsave('Fig S6b.pdf', device = cairo_pdf, height = 4, width = 2.5)
```

### HEI-2015

```{r}
ffq |> 
     filter(rarefied == 'Raw') |> 
     ggplot(aes(x = hei_plant_all, y = mean)) +
     geom_point(size = 2, alpha = 0.6) +
     facet_wrap(~study,
                nrow = 2) +
     ylim(0, 26) +
     labs(y = 'Mean pMR',
          x = 'HEI-2015 (plant\ncomponent)') 
```

```{r}
# ggsave('Fig 2d.pdf', device = cairo_pdf, height = 4, width = 2.5)
```

```{r}
ffq |> 
     filter(rarefied == 'Raw') |> 
     ggplot(aes(x = hei_non_plant, y = mean)) +
     geom_point(size = 2, alpha = 0.6) +
     facet_wrap(~study,
                nrow = 2) +
     ylim(0, 26) +
     labs(y = 'Mean pMR',
          x = 'HEI-2015 (non-plant\ncomponents)') 
```

```{r}
# ggsave('Fig S6c.pdf', device = cairo_pdf, height = 4, width = 2.5)
```

