---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r include=FALSE, echo=FALSE}
# Libraries
library(phyloseq)
library(scales)
library(tidyverse)
```

```{r include=FALSE, echo=FALSE}
# Plotting themes
theme_set(theme_bw() +
               theme(
                    axis.text = element_text(size = 12),
                    axis.title = element_text(size = 14,
                                              face = 'bold'),
                    strip.text = element_text(size = 12,
                                              face = 'bold')
                     )
)
```

# Read in data

```{r}
# Phyloseq object with paired samples pre- and post-optimization
ps <- readRDS('data/phyloseq_Experimental_optimization.rds')
```

# Pre-process

## Tidy

```{r}
samdf <- 
     ps@sam_data |> 
     data.frame() |> 
     rownames_to_column(var = 'row')
```

```{r}
# Recode seq date as pre- or post-optimization
samdf$seq_date <- 
     factor(samdf$seq_date,
            levels = c(20200304, 20210204),
            labels = c('Pre', 'Post'))

# Make a sample ID
samdf <- 
     mutate(samdf,
            id = paste(subj, CH_week, CH_weekday, sep = '_'))
```

Calculate PMR and add to sample data
Do for both all and food-only ASVs

```{r}
asvtab <- ps@otu_table@.Data

ps.food <- subset_taxa(ps, !is.na(superkingdom)) 
asvtab.food <- ps.food@otu_table@.Data

pmr <- data.frame(
     row = rownames(asvtab),
     pmr_all = apply(asvtab, 1, function(x){sum(x > 0)}),
     pmr_food = apply(asvtab.food, 1, function(x){sum(x > 0)})
)

pmr
```
```{r}
samdf <- full_join(samdf, pmr)
```

```{r}
# Add this new variable to widened set
# Get in wide form for side-by side comparison
samdf.wide <- 
     samdf |> 
     select(id, subj, CH_week, CH_weekday, seq_date, qubit, reads, 
            starts_with('pmr')) |>
     pivot_wider(names_from = seq_date,
                 names_sep = '_',
                 values_from = c(qubit, reads, starts_with('pmr')))
```

```{r}
names(samdf.wide)
```

# Analyze

## Qubit

```{r fig.height=4, fig.width=2.5}
ggplot(samdf,
       aes(y = qubit,
           x = seq_date,
           group = seq_date)) +
     geom_boxplot() +
     labs(y = 'DNA concentration (ng/ul)\nafter primary PCR',
          x = 'Combined\noptimization') +
     ylim(-0.2, 12) 
```
```{r}
# ggsave('Fig S1g.pdf', height=4, width=2.5)
```

```{r}
wilcox.test(samdf.wide$qubit_Post, samdf.wide$qubit_Pre,
            paired = TRUE,
            conf.int = TRUE)
```

## Read depth

```{r fig.height=4, fig.width=2.5}
ggplot(samdf,
       aes(y = reads,
           x = seq_date,
           group = seq_date)) +
     geom_boxplot() +
     labs(y = '*trnL* reads',
          x = 'Combined\noptimization') +
     scale_y_continuous(label = comma,
                        limits = c(0, 65000)) +
     theme(axis.title.y = ggtext::element_markdown())
```
```{r}
# ggsave('Fig S1h.pdf', height = 4, width = 2.5)
```

```{r}
wilcox.test(samdf.wide$reads_Post, samdf.wide$reads_Pre,
            paired = TRUE,
            conf.int = TRUE)
```

## Richness

```{r fig.height=4, fig.width=2.5}
samdf.wide |> 
     select(id, 
            starts_with('pmr_all')) |> 
     pivot_longer(cols = starts_with('pmr'),
                  names_pattern = '(pmr_food|pmr_all)_(Pre|Post)',
                  names_to = c('pmr', 'stage')) |> 
     mutate(pmr = gsub('pmr_', '', pmr),
            stage = factor(stage,
                           levels = c('Pre', 'Post'))) |> 
     ggplot(aes(x = stage,
                y = value)) +
     geom_boxplot() +
     labs(x = 'Combined\noptimization', y = '<br>*trnL* ASV count') +
     ylim(0, 35) +
     theme(axis.title.y = ggtext::element_markdown())
```
```{r}
# ggsave('Fig S1i.pdf', height = 4, width = 2.5)
```

```{r}
wilcox.test(samdf.wide$pmr_all_Post, samdf.wide$pmr_all_Pre,
            paired = TRUE,
            conf.int = TRUE)
```

