---
title: "Ordinations"
output: html_notebook
---

## Setup

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = file.path(getwd(), '..'))
```

```{r libraries, include=FALSE, echo=FALSE}
library(here)
library(phyloseq)
library(tidyverse)
library(vegan)
```

## Read in data

```{r}
# Joint phyloseq object
ps <- 
     here('data', 'processed', 'phyloseq', 'trnL_combined_ps.rds') %>% 
     readRDS()

ps
```

## Pre-process

### Filter?

## Analysis

### PCoA on Jaccard

```{r}
# Colorblind-friendly palette
pal <- brewer.pal(11, 'PiYG')
```

```{r}
# Refactor sample data, so CHOMP, ONR samples in background
sample_data(ps)$study <- factor(sample_data(ps)$study,
                                levels = c('Weight Loss',
                                           'Adult-1',
                                           'Adult-2',
                                           'Adolescent'))
```

```{r}
# Try using phyloseq wrapper
ord <- ordinate(ps, method = 'PCoA', distance = 'jaccard', binary = TRUE)
plot_ordination(ps, ord, color = 'study') +
     scale_color_manual(values = c(pal[2], 
                                   'gray30', 
                                   'gray70',
                                   pal[8])) +
     labs(x = 'PCo (principal co-ordinate) 1 (10.3%)',
          y = 'PCo 2 (6.4%)',
          color = 'Cohort') +
     coord_equal() +
     theme_bw()
```
```{r}
plotID <- paste(Sys.Date(), as.character(sample(000:999,1)), sep=".")

ggsave(here('results', 'ordination',
            paste0(plotID, '_Overall trnL composition by study, foods only with glomming, PCoA on Jaccard.pdf')),
       height = 4)
```

```{r}
# Sequencing batch
vegan::adonis(distance(ps, method = 'jaccard') ~ seq_date, 
              data = samdf)
```

```{r}
# Study
vegan::adonis(distance(ps.clr, method = 'euclidean') ~ study, 
              data = samdf)
```

```{r}
# Individual
vegan::adonis(distance(ps.clr, method = 'euclidean') ~ subj, 
              data = samdf)
```

